[env:bw16]
platform = realtek-ambz2
board = ai-thinker-bw16-typec
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=0
upload_protocol = ameba
